import bpy
#Notes: This will only work on mesh objects. Thats fine for any daes generated by Morphrender, but will not work on planes. 

#iterate over objects in scene
for o in bpy.context.scene.objects:
    if "CBb" in o.name:
        #Call the Decimate modifier
        modifier=o.modifiers.new("Decimate", type = "DECIMATE")
        #In the UI this is called "planar", scripting its called "DISSOLVE"
        modifier.decimate_type = "DISSOLVE"
        #angle limit in the UI is in degrees, in scripting you need to use radians. 
        modifier.angle_limit = 0.2617
        
        bpy.context.scene.update

print("done")